### ISSUE TITLE
KeyError: 'fadein_block'

### ISSUE THREAD

**Issue by WilliamHoo** [nashory/pggan-pytorch#48]
Hi, I was running the code, and i come with the problem below:

growing network[4x4 to 8x8]. It may take few seconds...
growing network[4x4 to 8x8]. It may take few seconds...
[*] Renew dataloader configuration, load data from ../../input.
Traceback (most recent call last):
 File "trainer.py", line 392, in <module>
   trainer.train()
 File "trainer.py", line 266, in train
   self.resl_scheduler()
 File "trainer.py", line 164, in resl_scheduler
   self.fadein['gen'] = dict(self.G.module.named_children())['fadein_block']
KeyError: 'fadein_block'

i set the trns_tick=4 and stab_tick=2 to speed up the process to see if there is any additional bug in the code. is that the problem is? is there any constraints on the value of trns_tick and stab_tick?

**Comment by July250229** [comment]
I met the same problem.

**Comment by ningmomomomomo** [comment]
I think it's nothing to do with trns_tick or stab_tick 
just change self.G.module.named_children() into self.G.module.model.named_children()
